name: exchange_app
description: "A Flutter application for currency exchange rates and conversions."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  envied: ^1.1.1
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.5  
  freezed: ^3.0.6
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  envied_generator: ^1.1.1
  flutter_lints: ^5.0.0
  mockito: ^5.4.4
  integration_test:
    sdk: flutter
flutter:

  uses-material-design: true
  fonts:
    - family: SFProText
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Regular.otf
        - asset: assets/fonts/SF-Pro-Text-Bold.otf
          weight: 600